### ISSUE TITLE
Improve documentation page

### ISSUE THREAD

**Issue by JagjeetChauhan** [SaashaJoshi/piQture#130]
this issue is linked with #116 issue.

**Comment by SaashaJoshi** [comment]
For more context, I have been referring to Spinx for creating the documentation do far. I hope [this website](https://www.sphinx-doc.org/en/master/) helps!

**Comment by JagjeetChauhan** [comment]
Ok, thankyou for assigning this task.

**Comment by SaashaJoshi** [comment]
Hi @JagjeetChauhan, any questions or updates?

**Comment by JagjeetChauhan** [comment]
I am working on it will give you update very soon.

**Comment by JagjeetChauhan** [comment]
@SaashaJoshi I have updated the file for data loader. Kindly review it and let me if any correction is needed.

**Comment by JagjeetChauhan** [comment]
@SaashaJoshi have you checked the document file I have created.
