### ISSUE TITLE
Implement Bitplane Representation of Quantum Images

### ISSUE THREAD

**Issue by Dljdd** [SaashaJoshi/piQture#131]
Implementing Bitplane Representation of Quantum Images Module for hacktober fest

Linked to #31

**Comment by SaashaJoshi** [comment]
Hi, incase you are looking for material on the chosen image representation method, you can refer to this paper: Hai-Sheng Li, Xiao Chen, Haiying Xia, Yan Liang, and Zuoshan Zhou. A Quantum Image Representation Based on Bitplanes. IEEE Access, 6:62396–62404, 2018. https://inspirehep.net/literature/2707463

**Comment by Dljdd** [comment]
thanks I've gone through the paper!
