### ISSUE TITLE
Implementation of QRMMI algorithm in the pipeline

### ISSUE THREAD

**Issue by Dabjazz** [SaashaJoshi/piQture#132]
This issue addresses the introduction and addition of QRMMI Algorithm to piQture library.

Linked to #31

**Comment by SaashaJoshi** [comment]
Citing important information from our discussion on Discord:

You can find the paper for the method here: Nanrun Zhou, Xingyu Yan, Haoran Liang, Xiangyang Tao, and Guangyong Li.
Multi-image encryption scheme based on quantum 3D Arnold transform and scaled Zhongtang chaotic system. Quantum Information Processing, 17(12):338, 2018.  https://ui.adsabs.harvard.edu/abs/2018QuIP...17..338Z/abstract
