### ISSUE TITLE
Change piQture logo

### ISSUE THREAD

**Issue by SaashaJoshi** [SaashaJoshi/piQture#71]
The logo still represents the QIPL library. Change the logo to represent piQture.

**Comment by Shivansh20128** [comment]
Hi @SaashaJoshi , do you have a particular logo in mind? Like do you want a new design or is the logo provided somewhere in the project? 
Great project btw, just found this and would definitely explore this more.
Thank you

**Comment by SaashaJoshi** [comment]
Hi @Shivansh20128, 
Nothing specific really. Be creative, haha.

**Comment by Shivansh20128** [comment]
Ahh okay great. Will try to do this as soon as I get some time.
Thanks

**Comment by Shivansh20128** [comment]
Hi again! I have created a PR for this. Since I also registered for Hacktoberfest, it would be great if we could do this under that.
Thanks
