### ISSUE TITLE
Add Docker Image yaml workflow

### ISSUE THREAD

**Issue by SaashaJoshi** [SaashaJoshi/piQture#73]
Required a docker image build, run, and push workflow.

**Comment by Abhinavks1405** [comment]
i want to try this , can you assign me .

**Comment by SaashaJoshi** [comment]
Hi @Abhinavks1405, great. Could you open a PR so that I can review the file and its location?

**Comment by Abhinavks1405** [comment]
@SaashaJoshi 
i have created a pr .
please tell me if any change is needed .
